default["wordpress-test"]["database"] = "wordpress-test"
default["mysql"]["server_root_password"] = "ilikerandompasswords"
default["wordpress-test"]["db_username"] = "wp-test-user"
default["wordpress-test"]["db_password"] = "212b09752d173876a84d374333ae1ffe"
default["wordpress-test"]["path"] = "/var/www/wordpress-test"
default["wordpress-test"]["server_name"] = "wordpress-test"
